import json

#dictionary with all the categories, questions, answers, and options for the player to choose from
questionaire = {
    "Geography": [{
        "question": "How many continents are there on Earth",
        "options": ["5", "6", "7", "9"],
        "answer": "7"},
        {"question": "What is the capital of Australia",
         "options": ["Adelaide", "Canberra", "Syndey", "Melbourne"],
         "answer": "Canberra"},
         {"question": "By land mass, which desert is the largest",
          "options": ["Sahara", "Kalahari", "Antarctic", "Gobi"],
          "answer": "Antarctic"},
          {"question": "Which country is the smallest in the world",
           "options": ["San Marino", "Vatican City", "Monaco", "Malta"],
           "answer": "Vatican City"},
           {"question": "Which ocean is the largest",
            "options": ["Indian", "Atlantic", "Pacific", "Arctic"],
            "answer": "Pacific"},
           {"question": "How many countries are in the United Kingdom",
            "options": ["1", "7", "4", "3"],
            "answer": "4"},
           {"question": "Which is the largest country in the world by area",
            "options": ["Russia", "USA", "China", "India"],
            "answer": "Russia"},
           {"question": "Which river is the longest in the world",
            "options": ["Amazon", "Nile", "Mississippi", "Euphrates"],
            "answer": "Nile"},
           {"question": "Which continent has the most countries",
            "options": ["Asia", "Europe", "Africa", "America"],
            "answer": "Africa"},
           {"question": "Which country has the largest population in the world",
            "options": ["Russia", "USA", "India", "China"],
            "answer": "India"}
         ],
    "History": [{"question": "In which year did World War II end",
                 "options": ["1939", "1921", "1945", "1999"],
                 "answer": "1945"},
                {"question": "Which war started in 1914",
                 "options": ["Cold War", "World War II", "World War I", "American Civil War"],
                 "answer": "World War I"},
                {"question": "Who was the first person to step on the Moon",
                 "options": ["Yuri Gagarin", "Buzz Aldrin", "Sally Ride", "Neil Armstrong"],
                 "answer": "Neil Armstrong"},
                {"question": "Which major historical event started in 1789 in France",
                 "options": ["Anglo French Wars", "World War I", "French Revolution", "Cold War"],
                 "answer": "French Revolution"},
                {"question": "Which wall fell in 1989, symbolizing the end of the Cold War division in Europe",
                 "options": ["Great Wall of China", "Wall of Hadrian", "Western Wall", "Berlin Wall"],
                 "answer": "Berlin Wall"},
                {"question": "Who was the first President of the United States",
                 "options": ["George Washington", "Abraham Lincoln", "Franklin D. Roosevelt", "Donald Trump"],
                 "answer": "George Washington"},
                {"question": "Which ancient civilization built Machu Picchu",
                 "options": ["Aztecs", "Mayas", "Incas", "Zapotec"],
                 "answer": "Incas"},
                {"question": "Which city was destroyed by the eruption of Mount Vesuvius in 79 AD",
                 "options": ["Rome", "Sparta", "Sodom", "Pompeii"],
                 "answer": "Pompeii"},
                {"question": "Which war was fought between the North and South regions of the United States in 1861 to 1865",
                 "options": ["The American Civil War", "The American Revolution", "The Battle of the Alamo", "The attack on Pearl Harbor"],
                 "answer": "The American Civil War"},
                {"question": "Which ancient Greek city-state was known for its military society and discipline",
                 "options": ["Sparta", "Mycenae", "Athens", "Macedonia"],
                 "answer": "Sparta"},
                ],
    "Science": [{"question": "How many elements are in the periodic table",
                 "options": ["118", "202", "60", "311"],
                 "answer": "118"},
                {"question": "What planet is known as the Red Planet",
                 "options": ["Sun", "Jupiter", "Earth", "Mars"],
                 "answer": "Mars"},
                {"question": "What force keeps us on the ground of Earth",
                 "options": ["Rotational", "Magnetic", "Gravitational", "Frictional"],
                 "answer": "Gravitational"},
                {"question": "What gas do plants absorb from the atmosphere for photosynthesis",
                 "options": ["Oxygen", "Nitrogen", "Methane", "Carbon Dioxide"],
                 "answer": "Carbon Dioxide"},
                {"question": "What is the main gas found in Earth's atmosphere",
                 "options": ["Oxygen", "Nitrogen", "Helium", "Carbon Dioxide"],
                 "answer": "Nitrogen"},
                {"question": "What part of the cell contains genetic material (DNA)",
                 "options": ["Membrane", "Cytoplasm", "Mitochondria", "Nucleus"],
                 "answer": "Nucleus"},
                {"question": "What planet is the largest in our solar system",
                 "options": ["Sun", "Mars", "Uranus", "Jupiter"],
                 "answer": "Jupiter"},
                {"question": "What is the closest star to Earth",
                 "options": ["Sun", "Andromeda", "Moon", "Proxima Centauri"],
                 "answer": "Sun"},
                {"question": "What is the boiling point of water at standard atmospheric pressure (in °C)",
                 "options": ["60", "1000", "90", "100"],
                 "answer": "100"},
                {"question": "What is the smallest particle of an element that still retains its chemical properties",
                 "options": ["Atom", "Neutron", "Electron", "Proton"],
                 "answer": "Atom"},
                ],
    "Maths": [{"question": "What branch of mathematics deals with shapes, angles, and spatial relationships",
               "options": ["Geometry", "Algebra", "Calculus", "Trigonometry"],
               "answer": "Geometry"},
              {"question": "What is the name of a number that is divisible only by 1 and itself",
               "options": ["Prime", "Decimal", "Even", "Composite"],
               "answer": "Prime"},
              {"question": "What is the name of a four-sided shape with all sides equal and all angles 90°",
               "options": ["Triangle", "Octagon", "Cube", "Square"],
               "answer": "Square"},
              {"question": "What is the value of π (pi) approximately equal to (to two decimal places)",
               "options": ["0.01", "4.13", "9.99", "3.14"],
               "answer": "3.14"},
              {"question": "What is the name of the result when a number is multiplied by itself",
               "options": ["Product", "Fraction", "Remainder", "Square"],
               "answer": "Square"},
              {"question": "What is the name of the mathematical operation that is the inverse of multiplication",
               "options": ["Addition", "Square Root", "Division", "Equation"],
               "answer": "Division"},
              {"question": "What do we call a sequence of numbers where each term is found by adding a fixed number to the previous one",
               "options": ["Fibonacci", "Arithmetic", "Random", "Geometric"],
               "answer": "Arithmetic"},
              {"question": "What is the name of a 3D shape where all points are the same distance from the center",
               "options": ["Sphere", "Cube", "Pyramid", "Cylinder"],
               "answer": "Sphere"},
              {"question": "What is the name of a number system that uses only 0 and 1",
               "options": ["Binary", "Decimal", "Roman", "Hexadecimal"],
               "answer": "Binary"},
              {"question": "What is the term for a mathematical statement that shows two expressions are equal (like x+2=5)",
               "options": ["Formula", "Equation", "Function", "Ratio"],
               "answer": "Equation"},
              ],
    "Technology": [{"question": "What does “CPU” stand for in computers",
                    "options": ["Central Processing Unit", "Computer Power Unit", "Core Performance Utility", "Computer Power Unit"],
                    "answer": "Central Processing Unit"},
                   {"question": "What does “RAM” stand for in computing",
                    "options": ["Random Access Memory", "Rapid Access Module", "Read Access Memory", "Remote Application Manager"],
                    "answer": "Random Access Memory"},
                   {"question": "What technology pioneer died of pancreatic cancer in 2011",
                    "options": ["Bill Gates", "Mark Zuckerberg", "Tim Berners-Lee", "Steve Jobs"],
                    "answer": "Steve Jobs"},
                   {"question": "What is the name of a malicious software program designed to damage or disrupt computers",
                    "options": ["Firewall", "Antivirus", "Malware", "Compiler"],
                    "answer": "Malware"},
                   {"question": "What is the name of the operating system developed by Microsoft",
                    "options": ["Linux", "macOS", "Windows", "Android"],
                    "answer": "Windows"},
                   {"question": "What do we call a program that manages computer hardware and software resources",
                    "options": ["Compiler", "Operating System", "Windows", "Browser"],
                    "answer": "Operating System"},
                   {"question": "What is the name of a network that connects devices within a small area like a home or office",
                    "options": ["WAN", "MAN", "LAN", "VPN"],
                    "answer": "LAN"},
                   {"question": "What is the term for software that is free to use and whose source code is publicly available",
                    "options": ["Proprietary software", "Open-source software", "Trialware", "Closed-source software"],
                    "answer": "Open-source software"},
                   {"question": 'What does "HTTPS" provide that "HTTP" does not',
                    "options": ["Encryption and secure communication", "Faster loading speed", "Data compression", "Offline access"],
                    "answer": "Encryption and secure communication"},
                   {"question": "What is the name of a software application used to browse the internet",
                    "options": ["Search engine", "Browser", "Server", "Chrome"],
                    "answer": "Browser"},
                   ],
    "General Knowledge": [{"question": "How many bones are in the human body",
                           "options": ["206", "201", "215", "180"],
                           "answer": "206"},
                          {"question": "How many continents are there on Earth",
                           "options": ["7", "5", "6", "8"],
                           "answer": "7"},
                          {"question": "Who wrote Romeo and Juliet",
                           "options": ["Charles Dickens", "Leo Tolstoy", "Shakespeare", "Homer"],
                           "answer": "Shakespeare"},
                          {"question": "What is the hardest natural substance on Earth",
                           "options": ["Iron", "Titanium", "Diamond", "Adamantium"],
                           "answer": "Diamond"},
                          {"question": "Who painted the Mona Lisa",
                           "options": ["Bob Ross", "Pablo Picasso", "Michelangelo", "Leonardo da Vinci"],
                           "answer": "Leonardo da Vinci"},
                          {"question": "What is the smallest prime number",
                           "options": ["0", "1", "2", "-1"],
                           "answer": "2"},
                          {"question": "What is the largest mammal in the world",
                           "options": ["Blue Whale", "Elephant", "Orca", "Giraffe"],
                           "answer": "Blue Whale"},
                          {"question": "What is the largest organ in a human body",
                           "options": ["Skin", "Liver", "Heart", "Brain"],
                           "answer": "Skin"},
                          {"question": "What is the currency of Japan",
                           "options": ["Yuan", "Euro", "Yen", "Bitcoin"],
                           "answer": "Yen"},
                          {"question": "What is the highest-grossing film of all time",
                           "options": ["Avatar", "Avengers: Endgame", "Star Wars: The Force Awakens", "Titanic"],
                           "answer": "Avengers: Endgame"},
                          ],
    "Astronomy": [{"question": "What is the largest planet in our solar system",
                   "options": ["Earth", "Sun", "Pluto", "Jupiter"],
                   "answer": "Jupiter"},
                  {"question": "What is the name of the galaxy that contains our Solar System",
                   "options": ["Cassiopeia", "Andromeda", "Orion", "Milky Way"],
                   "answer": "Milky Way"},
                  {"question": "What is the closest planet to the Sun",
                   "options": ["Moon", "Venus", "Mercury", "Pluto"],
                   "answer": "Mercury"},
                  {"question": "What is the name of a star explosion that can briefly outshine an entire galaxy",
                   "options": ["Black Hole", "Supernova", "Gamma Ray", "Big Bang"],
                   "answer": "Supernova"},
                  {"question": "What is the name of the telescope launched in 1990 that orbits Earth and captures deep spaces images",
                   "options": ["James Webb", "Galileo", "Apollo", "Hubble"],
                   "answer": "Hubble"},
                  {"question": "What is the name of the region around a black hole where not even light can escape",
                   "options": ["Vacuum", "Gravitational Pull", "Event Horizon", "Core"],
                   "answer": "Event Horizon"},
                  {"question": "What is the name of the phenomenon where the Moon passes between the Earth and the Sun, blocking sunlight",
                   "options": ["Solar Eclipse", "Lunar Eclipse", "Red Moon", "Blue Moon"],
                   "answer": "Solar Eclipse"},
                  {"question": "What is the name of the boundary in the Solar System beyond Neptune where many icy objects are found (including Pluto)",
                   "options": ["Galaxy", "Kuiper Belt", "Event Horizon", "Void"],
                   "answer": "Kuiper Belt"},
                  {"question": "What is the name of a rocky object that enters Earth's atmosphere and burns up, often creating a streak of light",
                   "options": ["Comet", "Debris", "UFO", "Meteor"],
                   "answer": "Meteor"},
                  {"question": 'What is the name of the planet known as the "Red Planet"',
                   "options": ["Mars", "Saturn", "Andromeda", "Sun"],
                   "answer": "Mars"},
                  ]
                          }

#storing the dictionary in a variable called data for better readability in the main code
data = questionaire

#save file as JSON
with open("questions.json", "w") as file:
    json.dump(data, file)


